echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-26 and learning DevOps"
echo "Hello, Good morning!"
echo "Hello bhava, kasa ahes? Majet na."
echo "Ekdum majet"
echo "Broooooooooo"
echo "Uno khelayla chala"